# -*- coding: utf-8 -*-
"""images_convolves.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1doJjBzyc5RF-WFvL90n3KlqeFSr5jSFZ
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive/')

image = cv2.imread('/content/drive/My Drive/OM_DOOR.png')
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
fig, ax = plt.subplots(1, figsize=(12,8))
plt.imshow(image)

filter_sharpen = np.array([[0, -1,  0],
                           [-1, 5, -1],
                           [0, -1,  0]])
                   
filter_top_edge = np.array([[ 1,  2,  1],
                            [ 0,  0,  0],
                            [-1, -2, -1]])

filter_bottom_edge = np.array([[-1, -2, -1],
                               [ 0,  0, 0],
                               [ 1,  2, 1]])

filter_right_edge = np.array([[-1, 0, 1],
                              [-2, 0, 2],
                              [-1, 0, 1]])

filter_left_edge = np.array([[ 1, 0, -1],
                             [ 2, 0, -2],
                             [ 1, 0, -1]])

filter_emboss = np.array([[-2,-1, 0],
                          [-1, 1, 1],
                          [ 0, 1, 2]])

filter_outline = np.array([[-1,-1,-1],
                           [-1, 8,-1],
                           [-1,-1,-1]])

filter_blur = np.array([[0.125, 0.25, 0.125],
                        [0.125, 0.5, 0.125],
                        [0.125, 0.25, 0.125]])

filters = [
           filter_sharpen, 
           filter_top_edge, 
           filter_bottom_edge, 
           filter_right_edge, 
           filter_left_edge,
           filter_emboss,
           filter_outline,
           filter_blur
           ]

filters_names = [
           'filter_sharpen', 
           'filter_top_edge', 
           'filter_bottom_edge', 
           'filter_right_edge', 
           'filter_left_edge',
           'filter_emboss',
           'filter_outline',
           'filter_blur'
           ]

ind = 0
for filter in filters :
  img = cv2.filter2D(image, -1, filter)
  fig, ax = plt.subplots(1,2,figsize=(21, 14))
  ax[1].imshow(image)
  ax[0].imshow(img)
  ax[0].set_title(filters_names[ind])
  ind=ind+1